name: Snyk Monitor Scanning
on:
  release:
    types: [published]
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  snyk-scan-ci:
    uses: grafana/security-github-actions/.github/workflows/snyk_monitor.yml@0d70b8f537da97b959bacf1b9c32be6d45f6cd64 # main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
